# Generated by Django 5.0.3 on 2024-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_image',
            field=models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='media/images/authors'),
        ),
    ]
