# Generated by Django 5.0.3 on 2024-04-03 19:43

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_profile_auth_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', ckeditor.fields.RichTextField()),
                ('blog_title', models.CharField(max_length=33)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('blog_image', models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='media/images/blogs')),
                ('Pen_name', models.CharField(max_length=7)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.tags')),
            ],
            options={
                'ordering': ['upload'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogging.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', ckeditor.fields.RichTextField()),
                ('story_title', models.CharField(max_length=33)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('story_image', models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='media/images/stories')),
                ('content_type', models.CharField(choices=[('story', 'Story'), ('poem', 'Poem'), ('novel', 'Novel'), ('short_story', 'Short Story'), ('essay', 'Essay'), ('drama', 'Drama'), ('script', 'Script'), ('article', 'Article'), ('review', 'Review'), ('other', 'Other')], max_length=20)),
                ('content_restrictions', models.CharField(choices=[('adult', 'Adult'), ('teen', 'Teen'), ('everyone', 'Everyone')], max_length=20)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20)),
                ('Author', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=100)),
                ('part_number', models.PositiveIntegerField()),
                ('part_desc', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='blogging.storypart')),
            ],
        ),
    ]
